### ISSUE TITLE
No chef-automate binary in fresh machine

### ISSUE THREAD

**Issue by chrisg-fastlane** [mattray/managed-automate2-cookbook#5]
On a brand new vagrant instance the cookbook fails because it's trying to run 'chef-automate' when it doesn't exist.

```
================================================================================
         Recipe Compile Error in /tmp/kitchen/cache/cookbooks/wbg_a006ba_managed_automate2_server/recipes/default.rb
         ================================================================================

         Errno::ENOENT
         -------------
         No such file or directory - /tmp/kitchen/cache/chef-automate

         Cookbook Trace:
         ---------------
           /tmp/kitchen/cache/cookbooks/managed-automate2/recipes/default.rb:22:in ``'
           /tmp/kitchen/cache/cookbooks/managed-automate2/recipes/default.rb:22:in `from_file'
           /tmp/kitchen/cache/cookbooks/wbg_a006ba_managed_automate2_server/recipes/default.rb:17:in `from_file'

         Relevant File Content:
         ----------------------
         /tmp/kitchen/cache/cookbooks/managed-automate2/recipes/default.rb:

          15:
          16:  # is Automate already installed?
          17:  installed = false
          18:  upgrade = false
          19:  restore = false
          20:
          21:  # is Automate installed?
          22>> versions = `#{chefautomate} version`.split
          23:  if versions[5].nil?
          24:    currentversion = -1
          25:  else
          26:    installed = true
          27:    currentversion = versions[5]
          28:  end
          29:
          30:  # if we have an upgrade URL or we have an upgrade file and a directory, it's an upgrade
          31:  if node['ma2']['upgrade']['url'] || (node['ma2']['upgrade']['file'] && node['ma2']['upgrade']['dir'])

         System Info:
         ------------
         chef_version=13.8.5
         platform=centos
         platform_version=7.4.1708
         ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
         program_name=chef-client worker: ppid=13441;start=00:06:47;
         executable=/opt/chef/bin/chef-client


         Running handlers:
       [2018-12-06T00:06:52+00:00] ERROR: Running exception handlers
         Running handlers complete
       [2018-12-06T00:06:52+00:00] ERROR: Exception handlers complete
         Chef Client failed. 7 resources updated in 04 seconds
       [2018-12-06T00:06:52+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2018-12-06T00:06:52+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2018-12-06T00:06:52+00:00] ERROR: No such file or directory - /tmp/kitchen/cache/chef-automate
       [2018-12-06T00:06:52+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by mattray** [comment]
I'll chalk this up as a documentation bug. You're supposed to use the airgap_bundle recipe to download the chef-automate command (and the .AIB) and put those in place so you can use them with the default recipe. It's meant to be air-gapped, so we can't have it reaching out to the Internet.
